apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  labels:
    app.kubernetes.io/name: gitops-app
spec:
  selector:
    app.kubernetes.io/name: gitops-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
